start cmd /k "cd C:\Users\devgu\Desktop\auto && python test2.py DAWN 30 1.5"
start cmd /k "cd C:\Users\devgu\Desktop\auto && python test2.py EMC2 30 1.5"
start cmd /k "cd C:\Users\devgu\Desktop\auto && python test2.py STX 30 1.5"
start cmd /k "cd C:\Users\devgu\Desktop\auto && python test2.py FLOW 30 1.5"
start cmd /k "cd C:\Users\devgu\Desktop\auto && python test2.py GRS 30 1.5"
start cmd /k "cd C:\Users\devgu\Desktop\auto && python test2.py BTG 30 1.5"
